### ISSUE TITLE
Hardcoded path in tests for local snap build

### ISSUE THREAD

**Issue by farshidtz** [canonical/matter-pi-gpio-commander#52]
This will work only if the snap is locally built and freshly installed:

https://github.com/canonical/matter-pi-gpio-commander/blob/a66a4967f6847807017690a32a21564a7493a4b2/tests/snap_test.go#L199

Should use the symbolic link: `/snap/matter-pi-gpio-commander/current/bin/test-blink`

**Comment by locnnil** [comment]
As [showed here](https://github.com/canonical/matter-pi-gpio-commander/actions/runs/8454689721/job/23160330803?pr=58#step:6:62), the approach of only use the symlink to `/snap/matter-pi-gpio-commander/current/bin/test-blink` doesn't work.
